name: windows-artifacts

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

concurrency:
  group: windows-artifacts-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2025

    env:
      CARGO_INCREMENTAL: "0"
      RUSTC_WRAPPER: "sccache"
      RUSTUP_WINDOWS_PATH_ADD_BIN: "1"
      SCCACHE_GHA_ENABLED: "true"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-pc-windows-msvc

      - name: Compile with sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        id: cache-cargo-vendor
        with:
          path: |
            vendor
            .cargo/config
          key: cargo-deps-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Vendor dependencies
        if: steps.cache-cargo-vendor.outputs.cache-hit != 'true'
        shell: bash
        run: cargo vendor --locked --versioned-dirs >> .cargo/config

      - name: Build wezterm
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p wezterm --release

      - name: Build wezterm-gui
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p wezterm-gui --release

      - name: Build wezterm-mux-server
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p wezterm-mux-server --release

      - name: Build strip-ansi-escapes
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p strip-ansi-escapes --release

      - name: Package
        shell: bash
        run: bash ci/deploy.sh

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v7
        with:
          name: wezterm-windows-${{ github.sha }}
          path: |
            WezTerm-*.zip
            WezTerm-*.exe
            target/release/*.exe
          if-no-files-found: error
          retention-days: 14
